[build]
  functions = "netlify/functions"
  publish = "."

# This turns https://cdn.gippslander.com.au/get-jobs into a working API
[[redirects]]
  from = "/get-jobs"
  to = "/.netlify/functions/get-jobs"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
